config/routes.rb
Rails.application.routes.draw do
  resources :games
  devise_for :users
  root 'pages#home'
  get 'dashboard' => 'pages#dashboard'

   post '/buy/:slug', to: 'transactions#create', as: :buy 
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
        can :read, :all
     can :manage, Game do |game| 
            game.try(:user) == user 
        end
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/game.rb
class Game < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged 

	belongs_to :user
	has_many :sales 

	has_attached_file :image 

	validates_numericality_of :price, 
		greather_then: 49, message: "Must be at least 50 cents"
	

		validates_attachment_content_type :image, 
		content_type:  /^image\/(png|gif|jpeg)/,
		message: "Only images allowed"

    validates :image, attachment_presence: true 
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	before_create :populate_guid
	belongs_to :game


		include AASM
    
    aasm column: 'state' do 
    	state :pending, initial: true 
		state :processing 
		state :finished 
		state :errored 
		event :process, after: :charge_card do 
			transitions from: :pending, to: :processing
		end

		event :finish do 
			transitions from: :processing, to: :finished 
		end

		event :fail do  
			transitions from: :processing, to: :errored 
		end
    end

def charge_card 
		begin
			save! 
			charge = Stripe::Charge.create(
				amount: self.amount, 
				currency: "usd",
				card: self.stripe_token,
				description: "Game Sale"
				)
			self.update(stripe_id: charge.id)	 
			self.finish! 
		rescue Stripe::StripeError => e
			self.update_attributes(error: e.message)
			self.fail!
		rescue Stripe::StripeError => e
			
		end
	end

	private 

		def populate_guid
			self.guid = SecureRandom.uuid()
		end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception| 
  	redirect_to root_path, notice: "You are not authorized to access this area"
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

# Ensure the user is logged in.
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /games
  # GET /games.json
  def index
    @games = Game.where(availability: true)
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
   authorize! :manage, @game
  end

  # POST /games
  # POST /games.json
  def create
    
  @game = current_user.games.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    authorize! :manage, @game
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    authorize! :manage, @game
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.friendly.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :genre, :description, :price, :availability, :image)
      
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  	 if current_user 
        redirect_to games_path
      end
      @games = Game.last(4)
  end

  def dashboard
  	 @games = current_user.games
  	 @purchased = Sale.where(buyer_email: current_user.email)
  	 @sales = Sale.where(seller_email: current_user.email)
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController< ApplicationController
	def create
		game = Game.find_by!(slug: params[:slug])
		sale = game.sales.create(
			amount: game.price, 
			buyer_email: current_user.email, 
			seller_email: game.user.email, 
			stripe_token: params[:stripeToken])
		sale.process!
			
		if sale.finished?
			redirect_to pickup_url(guid: sale.guid), notice: "Transaction Successful"
		else
			redirect_to game_path(game), notice: "Something went wrong"
		end
	end


	def pickup
		@sale = Sale.find_by!(guid: params[:guid])
		@game = @sale.game
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for(@game, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :name, required: true, label: false, placeholder: "Name", input_html: { class: "form-control"} %>
    <%= f.input :genre, required: true, label: false, placeholder: "Genre", input_html: { class: "form-control"} %>
    <%= f.input :description, required: true, label: false, placeholder: "description", input_html: { class: "form-control"}, rows: 5 %>
    <br>
    <%= f.input :price, required: true, label: false, placeholder: "price", input_html: { class: "form-control"} %>
     <%= f.input :image %>
    
    
    <div class="checkbox text-center">
      <p>Availability</p>
      <%= f.input :availability, required: false, label: false %>
    </div>   


    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>

app/views/games/_game.html.erb
 <div class="col-md-3">
    <div class="thumbnail">
        	<%= link_to game_path(game) do %>
          <%= image_tag game.image.url(:original), class: "img-responsive" %>
        <% end %>

    <div class="caption">
      <p><strong><%= link_to game.name, game_path(game) %></strong></p>
       <p>$<%= game.price.to_f / 100 %></p>
   </div>
    </div>
  </div>

app/views/games/edit.html.erb
<h1 class="text-center">Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row">

    <%= render @games %>

</div>

app/views/games/new.html.erb
<h1 class="text-center">New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6">
      <%= image_tag @game.image.url(:original), class: "img-responsive" %>
    </div>

    <div class="col-md-6">
      <h3><%= @game.name %> - <%= @game.genre %></h3>
      <p class="justify"><%= @game.description %></p>
      <h4 class="text-right">$<%= @game.price.to_f / 100 %></h4>

    <% if current_user %>



<%= form_tag buy_path(slug: @game.slug) do  %>
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-amount=" <%= @game.price %>"
    data-name="MarketPlace"
    data-description=" <%= @game.name %>"
    data-email="<%= current_user.email %>"
    data-locale="auto">
  </script>


 
      <% end %>
  <% else %>
      <p>Please login first to Buy</p>
    <% end %>


    </div>

  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Gaming Market Place", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          
          
          <ul class="nav navbar-nav navbar-right">
            <%= link_to "Games", games_path  %>
          
          <% if current_user %>
           <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete %>
          
          <% else %>
          
            <li><%= link_to "Login", new_user_session_path %></li>
          
          <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>

	<% flash.each do |type, message| %>
	<div class="alert alert-info fade-in">
		 	<button class="close" data-dismiss="alert">X</button>
		 	<%= message %>
		  </div>
		<% end %>

	<div class="container">
			<%= yield %>
		</div>
</body>
</html>

app/views/pages/_games.html.erb
<table class="table table-condensed"> 
	<thead> 
		<tr> 
			<th>Id</th> 
			<th>Name</th> 
			<th>Available</th> 
			<th></th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @games.each do |game| %> 
		<tr> 
			<td><%= game.id %></td>
			<td><%= link_to game.name, game_path(game) %></td> 
			<td><%= game.availability %></td> 
			<td><%= link_to "edit", edit_game_path(game) %></td> 
		</tr> 
		<% end %>
 </tbody> 
</table>

app/views/pages/_sales.html.erb
<table class="table table-condensed"> 
	<thead> 
		<tr> 
			<th>Name</th> 
			<th>Date</th> 
			<th>Buyer</th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @sales.each do |sale| %> 
		<tr> 
			<td><%= link_to sale.game.name, pickup_path(sale.guid) %></td> 
			<td><%= time_ago_in_words(sale.created_at) %> ago</td> 
			<td><%= sale.buyer_email %></td> 
		</tr> 
		<% end %>
 </tbody> 
</table>

app/views/pages/dashboard.html.erb
<div class="row">
	<h1 class="text-center">Dashboard</h1>
	
	<div class="col-md-4">
		<h3 class="text-center">
			Games <%= link_to "New Game", new_game_path, class: "btn btn-primary btn-sm" %>
		</h3>  

			<%= render 'games' %>

		

	</div>

	<div class="col-md-4">
		<h3 class="text-center">Purchased</h3>  
		<%= render'purchased' %>
	</div>

	<div class="col-md-4">
		<h3 class="text-center">Sales</h3>  
		<%= render 'sales' %>
	</div>

</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h1>Welcome to Gaming Market Place</h1>
    <p>Easiest Way to buy & Sell Your Favorite Games!</p>
    
    <%= link_to "Games", games_path, class: "btn btn-primary" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
</div>

<div class="row">
	<%= render @games %> 
</div>

app/views/transactions/pickup.html.erb
<div class="row text-center">
	<br>
	<h1>Congratulations! </h1> 
	<br>
	<h3>Thanks for buying <i>" <%= @sale.game.slug %> "</i> <br>
	It will be shipped to your address  </h3>
</div>